### ISSUE TITLE
Broken comet.tpl

### ISSUE THREAD

**Issue by wolski** [lcb/applicake#8]
The commit : https://github.com/lcb/applicake/commit/5725621f1f88af74c040c1d5a99ed3cc8fb1d746

Breaks comet. You pushed an old comet.tpl file into the master.

-# comet_version 2015.02 rev. 0
+# comet_version 2013.02

Did't we agree to upgrade comet?

**Comment by lcb** [comment]
Sorry my bad, checked it development stuff by accident. will try to update, too.
